
version: '3.8'
services:
  firebase:
    build: .
    ports:
      - "4000:4000" # Emulator Suite UI
      - "4400:4400" # Hub
      - "4500:4500" # Logging
      - "5001:5001" # Functions
      - "8080:8080" # Firestore
      - "8085:8085" # Realtime Database
      - "9000:9000" # Hosting
      - "9099:9099" # Auth
      - "9199:9199" # Storage
      - "9299:9299" # Eventarc
      - "9399:9399" # Data Connect
    volumes:
      - .:/app
